### ISSUE TITLE
doesnt load blueprint

### ISSUE THREAD

**Issue by RubenNL** [d4rkc0d3r/FactorioSimulation#1]
Hey d4rkc0d3r, i'm having a problem, it doesnt find my inputs/outputs.
this is a image of the blueprint i want to test:
![image](https://cloud.githubusercontent.com/assets/15885455/25231406/1287f53e-25d8-11e7-8717-0fc3e9522b79.png)
the blueprint string is: 
`H4sIAAAAAAAA/6WVwWqEMBCGX0U8x0Wzbi8lzyJWp0vAnUgy0l0k794oUpB01ZiLiuT3m0w+xlYlnWrqLqnEKBuFRoyjxBaeomBG3rHuxEivHkQqCR4pw/rh
nr9rQxnpGk2vNGVf0FFqLVuSfC9p+k4SgXYZywBJkoQJ/P7jrFfGrVIoxqfIruzlLpa1UkMzv+UOHpTmZ9PFHvtvc+scn6mX20lu7mHL42G/5vJIzfnl5rUq
gMo96kdgmNvjAf9UA2izE3mUUEWMUFvoLZ/y0z4VMTXvlTy4MaDvWrn7O5VX6JItgwL7wQ2SI2pOFZze/HJgR0CRbZ7dOD1rpnCUV1vhDa+KKK1irNpq1b5V
/D+p1EC+VXt2hDcuvm/XgGmXz+tXLLv8YRF+qiK1nxpo0JhUn4DtL8s3V83mBwAA
`
this is the output of the script:
![image](https://cloud.githubusercontent.com/assets/15885455/25231452/30d5f590-25d8-11e7-831f-65d53350878a.png)

I'm sure it loads the file, because if i try an file that doesnt exist, it gives an error.

**Comment by d4rkc0d3r** [comment]
The blueprint string was ordered differently, did you use a different blueprint string mod than I do? I use https://mods.factorio.com/mods/DaveMcW/blueprint-string

**Comment by RubenNL** [comment]
i use foreman.

Verzonden met AquaMail voor Android
http://www.aqua-mail.com


Op 24 april 2017 13:31:30 schreef d4rkc0d3r <notifications@github.com>:

**Comment by d4rkc0d3r** [comment]
Well it should work now with that as well.
