### ISSUE TITLE
Output/Input Balance is flipped

### ISSUE THREAD

**Issue by Xoriun** [d4rkc0d3r/FactorioSimulation#10]
Testing a 2 to 4 Balancer gives me:

Loading a 2 to 4 balancer with dimensions 4x6 and 5 splitters
Output balance: 2/2
Input balance: 4/4
Throughput under full load: 100%
Min Throughput with all combinations: 100%

Shouldn't it be:
Input balance: 2/2
Output balance: 4/4

**Comment by d4rkc0d3r** [comment]
No that is correct. It tests how many input belts lead to output balance and how many of the output belts draw from all inputs equally.
