### ISSUE TITLE
Wrong throughput percentage

### ISSUE THREAD

**Issue by Xoriun** [d4rkc0d3r/FactorioSimulation#11]
When testing the attached balancer with -tallcpu, the program instantly finishes and results in a minimum throughput of 6900%.
[balancer.txt](https://github.com/d4rkc0d3r/FactorioSimulation/files/5438999/balancer.txt)

**Comment by Xoriun** [comment]
I compacted the balancer a little bit, but still get the exact same behavior, so I doubt that this has to do specifically with my bp.
[balancer2.txt](https://github.com/d4rkc0d3r/FactorioSimulation/files/5444835/balancer2.txt)

**Comment by d4rkc0d3r** [comment]
-tall can only do balancers with up to 30 in/out belts. Tough since combinations rise exponentially, -tall is pretty much pointless to use for anything larger than a 16 to 16 balancer. For such large balancers there is -trandom which runs random combinations until you kill the program.

**Comment by Xoriun** [comment]
OK, will try the random then
But a warning message should be displayed if it's not supported.
And it would bei nice, if 32 was still supported, since it is a nice power of 2.

**Comment by d4rkc0d3r** [comment]
I made it gracefully tell you that your balancer is too large for `-tall` now.
> And it would bei nice, if 32 was still supported, since it is a nice power of 2.

My 24 to 24 already has an estimated time of 12 days with `-tall`, with all the performance improvements of this release. There really isn't any point to support larger balancers in that mode. `-tlocal` & `-trandom` were made for those.
