### ISSUE TITLE
False positive on unlimited throughput

### ISSUE THREAD

**Issue by ScarabWasTaken** [d4rkc0d3r/FactorioSimulation#14]
I was testing the idea that an n-n UTU balancer can function as an m-m UTU balancer without looping outputs where m<n  

The following (on the right) 6x6 ballancer when limited to the left 4 inputs and the right 4 outputs loses throughput. Despite being marked as 100% on all categories with your script. This is the only combination of 4 inputs to 4 outputs that loses throughput. 
The balancer on the left is the fixed version.
![Capture](https://user-images.githubusercontent.com/85250052/120527209-fa4f1500-c3d1-11eb-9ca0-22b07a9eeb1e.PNG)

Blueprint:
`0eNqlmetqq0AUhd9lfpvi3NVXKeWQtEMREhUvh4bgu5+YUMhJXVVn/QqG5JvlnrX37K0XcTgOoWnLqhfFRZTvddWJ4vUiuvKz2h+n7/pzE0Qhyj6cRCKq/Wm6Cl9NG7pu17f7qmvqtt8dwrEXYyLK6iN8iUKOyWpI1xzLvg/tw9/V+JaIUPVlX4a7oNvF+U81nA7XXxZySUoimrq7/r2upvUnRSp/sYk4i2Kn1YsdJ4FPULUdqtMlqI6AyiWoiYCqJailYprOQx0FlfNQT20UUJpRGwWgOaUU3L5MKamIKilTgQBIRVGRVo2ryIyhsjttMtYsLSKdlP/WqDJA/ZlPw7W6tZ9tff2E3Ow/bvJdOuuhb4apwv5cx22JhU4XYuGjVOebVWdMZsCY50xmIKpKN0VY/R5hReUZ1KgoD3tAjTi9Hhzsb174KNvwfv+Fm1vDRPnXAcXUKbZSsaNchpT7TXGQCzuXUS5DGnOKCrTqlNozC6gyylcG0FRMXXzYdbOuLmod5QIUA6pRhFRLUVGEHVXBUPvtKap+rgdqbo2MqpLr1sjJc1k9+q+sgP0Ml4oajCuSOuzVmgCZuARNn7ZhMUENNdCtvBcubdHQyKUt2lsubcHYYLi0BWODyciWXK5LonzTdJL/HgqbRp1jIASWS0Wkkeo+JehpraaooP+2hqnWkGpjdgnSXIyDYByp5yWQSj0wkdmaTttS/ea6NVwa8yxBgg7ZScqzoEN2KspdSCM11UGNhmkdINVyx7r0q0q2czEjPgyw54aFtaKpGQ9GPKccDGYGn1JUMDN4STkZaVWUkxGVyzoUAS7rENVSJwaKgKOoN61vyf0tUvHw5ioRf0Pb3bvpTBqfK6/z1EnvxvEfYKrWJQ==`

**Comment by d4rkc0d3r** [comment]
Oops, looks like I had an overzealous optimization. `-tall` was only checking combinations of up to 3 belts used which was too little to find this. I fixed this and made a new release v1.10
Thanks for the bug report
