### ISSUE TITLE
Completely broken for balancers that aren't 2^n

### ISSUE THREAD

**Issue by amdepott** [d4rkc0d3r/FactorioSimulation#17]
For example, the classic 1-3 balancer

![image](https://github.com/user-attachments/assets/88b47294-dc42-4fde-a7d2-c2027833dd7e)

`0eNqdldFugzAMRf/Fz2GqA7SF79jbNCFosylSGqLEVEUV/74A2la1QS15I07u8Q224QqN6oSxUhOUV5CHVjsoP67g5Leu1Rij3ggo4SwtdT7CQNenMTCfSBAGBlIfxQVKHNgKZXqj5KuU7zfKdPhkIDRJkmK2Pi36SnenRlhv6k8tLsYK5xKytXamtZQ0QpGnm9Z5eavH1B6Z4FvOoJ8fhtHZHZI/IJ1RksjvBWAzahNGpevdbZ64y1YjnxHzeOLCtberiXhLZHCUVhzmbeSBBLv4qi9Y3q8vOk5WpTYdVX7GWut5Xq/EF0EgQxHfCw8vJQvwcbPiCr9kfIGL0dXEe9/7EJ9H8xdqiWl8e/AFZBZfvSVk/Nzxl4YE48cwlMB/iCWJk6f9/1QYqNqTfAyrtKKuampV68PUcWdh3aTNt7zIiiLP+C7lexyGHydMMXA=`

Gives the following result
![image](https://github.com/user-attachments/assets/24dcadb3-81f6-4314-af5b-a200c9ad40d9)

**Comment by d4rkc0d3r** [comment]
It doesn't support the priority settings.
Edit: actually it might be the new directions in 2.0 that break stuff...

**Comment by amdepott** [comment]
![image](https://github.com/user-attachments/assets/3957e0f2-75e9-4753-a0f7-614d940af29c)
 Priority is not the issue

**Comment by d4rkc0d3r** [comment]
Yeah as I said in the edit. Its very likely an issue since 2.0 blueprints have more possible directions so all the belt directions are a complete jumble compared to what it expects.
Try downgrading factorio to 1.1 and exporting the blueprint from there.

**Comment by d4rkc0d3r** [comment]
v1.11 can now handle blueprints exported from factorio 2.0.
I also added a warning that it ignores the splitter priorities.
