### ISSUE TITLE
-tall doesn't do what the tip suggests

### ISSUE THREAD

**Issue by JohnyDL** [d4rkc0d3r/FactorioSimulation#2]
-tall's tip: tests all throughput combinations where more or equal to two inputs and outputs are used N specifies how many threads will be launched and is 1 by default

This seems to suggest that it tries every combination with 2 or more inputs and 2 or more outputs, I tested this with a 64 to 64 balancer that I'd expected to take forever to test like this.

I mean seriously there's some 3.2*10^38 permutations to iterate through for that set up, and the program ran in fractions of a second only telling me the throughput under full load = 100% while -t2 testing every 2 inputs to every 2 outputs takes minutes.

I'd hoped to leave it on over night and see if I have any unforeseen bottle necks built into the design so if this is a 'feature' to stop the program causing problems with large balancers that will never finish I have a few suggestions.

A providing a break out/quit method other than CTRL + Break (force terminate the program)

B including ongoing statistics while only testing a sample of each case in each pass,

Case example 1: 2 inputs or outputs, initially target tests at the two closest together inputs/outputs (25% of iterations as probably multiple places where inputs are adjacent), the two furthest apart (5% of iterations probably only one instance of the furthest apart but go for the next most and the next most until all these slots are taken) and a middle ground (45% most cases are somewhere in the middle of the two extremes my 64to64 has a lot that're 48 apart so test a number of there) and continue through the rest systematically.

Case example 2: N inputs again test inputs that're as close together as possible, let as evenly distributed as possible take the place of the mid ground, and with the largest gaps (with clusters on each end) take the as far apart as possible, continuing systematically.

My best guess is somewhere around 1000 iterations per case per pass is a good number, it'd let you pick 32 input sets in a case and 32 output sets in a case and iterate them against the other, of each case. In my 64to64 that'd be 1024 tests * 3949 cases and would take about as long for a single pass as the -t2 test takes, you could reverse engineer the number of tests based on that idea each pass should take about the same amount of time as -t2 would on the same data, it wouldn't provide certainty for all options obviouslty, but it could show roughly how accurate it is sure one test might have an minimum through put far lower than the rest that you never hit but the chances of that happening are minimal, so long as all inputs connect to all outputs

Here's how I'd display the data

Inputs | Outputs | Minimum throughput | Count perfect (Pass/fail) | Tests | Total needed for certainty | completion
---|---|------|---------|--------|-----------|----------------------
2 | 2 | 100% | 1000/0 | 1000 | 4064256 | 0.02%
2 | 3 | 66% | 253/747 | 1000 | 83991624 | 0.001%
3 | 2 | 100% | 1000/0 | 1000 | 83991624 | 0.001%
2 | 4 | 50% | 1000/0 | 1000 | 1280918016 | 0.00008%

And so on filling it in as the program does passes (I rather like the pattern of test 2 in to N out then 2+1 to N-1 then 2+n to N-n all the way to N to 2, I don't know why although filling in the NtoN cases (and the near misses) first, then the Max/2^n to Max/2^m cases before systematically doing the rest would likely be the most useful for the most people)

For the count perfect test introduce say Max inputs*Max outputs*inputs in case*outputs in case *some constant as the number of items added at each input (to give the balancer the best chance of being able to pass count perfect if the number of items isn't at least divisible by the outputs that's not a fair test) and count the items that output on each line if this number is the same on all lines (or within 1 given there's going to be loss to empty sections of the balancer) then it passes otherwise it fails, to be totally count perfect it should pass every time (at least on the 2^n to 2^N cases)

And again if you link it to the ability to quit you can let it keep running as long as the user can stand and have it save the output as a .txt or .cvs file for the user

By the way I know huge amount of criticism in here but actually still love the program wouldn't have spent over an hour filling a issue report with ideas if I didn't. wish I could be more help than just ideas.

**Comment by d4rkc0d3r** [comment]
>This seems to suggest that it tries every combination with 2 or more inputs and 2 or more outputs, I tested this with a 64 to 64 balancer that I'd expected to take forever to test like this.

It does what it says. BUT a 64 to 64 would take so long that it isn't even supported. It is unspecified behaviour since I only tested up to 16 belt balancer with that option. To be more technical, I use 32 bit ints to iterate over all possible combinations, but obviously this can't work with 64 input belts.

>number of items

There are no discrete items in this simulation. It uses floats for throughput. That is blue belt has throughput 1.0, red 2.0/3.0 and yellow 1.0/3.0. Thus the count perfect test already has some arbitary low threshold to account for floating point shenanigans.

Now for an actual answer to your request. Would it be ok for your usecase if I make an option to run random tests continuously while reporting the minimum encountered throughput? Because that would be way easier to implement than the things you proposed.

**Comment by JohnyDL** [comment]
Totally understand yeah, it would take millennia, Random would work but it's less likely to find those cases most likely to cause problems (adjacent inputs and outputs and evenly distributed) so I'll also provide pseudo code for the way I was thinking (with the most complicated bits removed I don't think it was overly clear)
Didn't check the way you did the count perfect stuff probably should have :) sorry but again I've commented with no thought to how your code works so I don't learn. 

[code]
iteration=0
targetI=1
targetO=1
inputs[] = from file
outputs[] = from file
WHILE doIterations=true
  IF iteration==0
    inputSets[] = generateInitialSets(inputs)
    outputSets[]=generateInitialSets(outputs)
    targetI = inputSets.length()
    targetO = outputSets.length()
  ELSE
    // i tells you which triangles have been completed
    i=floor(1/2 (-sqrt(8 iteration) - 1))
    // j tells you where in this triangle you are
    j=(iteration - 1) - (i*(i+1)/2)
    // sequence in theory [j, i-j+1]: [0,0] [1,0] [0,1] [2,0] [1,1] [0,2] [3,0] [2,1] [1,2] [0,3]....
    inputSets[]=GenerateLogicalSets(inputs, j, targetI)
    outputSets[]=GenerateLogicalSets(outputs, i-j+1, targetO)
  FOREACH iSet in inputSets
    FOREACH oSet in outputSets
      test (iSets, oSets)
    END
  END
  iteration ++
End

//generates the packed and distributed initial sets
generateInitialSets(inputs){
sets = newArray[];
// i the number of targets to make in this set
FOR i=1 to inputs.length()
  // j the first target in this set
  FOR j=1 to inputs.length()
    // add a set to the sets array starting at j and using the next i inputs if reached end of inputs return to the first
    FOR k=0 to i-1, k++
      set[k]=inputs[mod(j+k, inputs.length())]
    END
    sets.push(set)
    IF i != 1 AND i != inputs.length()
      n=FLOOR(inputs.length()/i)
      // add a set to the sets array starting at j and using the i inputs n distance apart if reached end of inputs return to the first
      FOR k=0 to i-1, k++
        set[k]=inputs[mod(j+k*n, inputs.length())]
      END
  END
END
RETURN sets
}

generateLogicalSets(inputs, iteration, target){
sets = newArray[];
i=(iteration)*target
WHILE sets.length < target
  j=i
  For n=0 to inputs.length()
    IF mod(j, 2) != 0
      sets.push(inputs[n])
    END
    j = floor (j/2)
  i++
END
RETURN sets
}
[/code]

Having written all of this I'm thinking that having this (or at least the initial sets) as one option and random as another would provide the best combination of tests

**Comment by d4rkc0d3r** [comment]
Use -tlocal16 for your 64 to 64 balancer with version 1.6

**Comment by JohnyDL** [comment]
Thanks a lot super awesome :)
