### ISSUE TITLE
UG Entrance should only connect with Exits of the same type

### ISSUE THREAD

**Issue by raynquist** [d4rkc0d3r/FactorioSimulation#3]
For testing balancers using BeltZip.

Test case:
> 0eNqdlNFOwzAMRX9l8nOKmqzroI98BgihdGQjUpZEiQObpv477jbGRDsR+pTEio/vlS0foDVJ+aAtQnMAvXI2QvN8gKg3Vpo+hnuvoAGNagsMrNz2L7XzQcVYRG80ogrQMdD2Te2g4R3LTscgbfQuYNEqg1cQ0b0wUBY1anUSdHzsX23atlSu4belMPAuUqKzfX2CFeXdgsGeLlXXi/uFEgNUIhFhExydJ2FDJD8B5yT57NAl9Kn3MCgw/8v3AF9+00do1STnYgy1uKDWMmKG7bMunuO6ngYvf9ja3kAvL+j8TmVpvv8/OEfvw8QBGG0aL6cMAB9F8emjLzJ8c/Fv42c6TT4tgOPSaK5WFAMjKY9iomilkXalwuxT4/ssJq/C2iSX4uyRyE/a0+8PFeKRXVeVqJfzZV3TCvgCmGysyg==

**Comment by d4rkc0d3r** [comment]
I fixed it and made a new release: https://github.com/d4rkc0d3r/FactorioSimulation/releases/tag/v1.7
