### ISSUE TITLE
4-balancer should also work as a 3:4 balancer

### ISSUE THREAD

**Issue by raynquist** [d4rkc0d3r/FactorioSimulation#5]
![3-4-balancer](https://user-images.githubusercontent.com/31404369/30244632-a5f54b36-9587-11e7-8caf-8103bd243470.png)

Standard 4-balancer minus 1 input should work as a 3:4 balancer.  In the screenshot I slowed down the belts a bit to avoid the splitter quirk.  However the program doesn't think it's balanced.

> Loading a 3 to 4 balancer with dimensions 4x7 and 4 splitters
Output balance: 3/3
Input balance: 0/4
Throughput under full load: 100%

Flipping the balancer around would not work as a 4:3 balancer as 1 output belt would get more items pushed onto it than the other 2.  But 3:4 does not have the same problem; all 3 belts are pulled evenly.

**Comment by d4rkc0d3r** [comment]
>However the program doesn't think it's balanced.
>Output balance: 3/3

Looks to me like the program thinks it is output balanced. I see no issue here.

**Comment by raynquist** [comment]
I believe input should also be balanced.  From what I understand, input balanced means each output draws from all inputs evenly, and this balancer does that.

**Comment by d4rkc0d3r** [comment]
[It draws twice as many items from the purple lane.](https://i.imgur.com/vEJCH9X.png)
