### ISSUE TITLE
Wrong numbers on the belt balancing tool

### ISSUE THREAD

**Issue by Wertoyou** [d4rkc0d3r/FactorioSimulation#9]
The Lane balancer I made gives the wrong max throughput number in your belt balancing tool. <details><summary>This blueprint string should have 100%</summary>
<p>

0eNqlm+tOIkEQhd9lfoPp6nvzKhuz8TLZTKIDGQajMbz7DoKrgWbn1PEXEeTrmq7b6bZ8b+6fdu1m6PqxWb033cO63zarX+/NtvvT3z0d3hvfNm2zal66YdxN7yya/u758MbxN5ax2S+arn9sX5uV7BeVb3Zj+/z1tfZ1M7Tb7XIc7vrtZj2My/v2afwGsVUIsrzb3y6ath+7sWuPT/Hxw9vvfvd83w6TfXNWLJrNejt9fd0flp6Qy7Jo3qYXP63y2A3tw/GzeLDxDG718ATD3QV8u3nqxnH67BKbj1h3E+bBXm91hK0OeniA4VEP9zA86eGuCvcVeNbDLWx50cMFhotR0w0OF0WQiyLGRZ+a+H7LZWrupnI0/BnW0+sV/ClWzmyfwvNU7da7cbM7FMXL5fQJ6/Bn0Sesrz5JFR5ZOJBSkhSx81ljoNjJCnDUBKU+UfF2YfV5mnE430YdQLc03QJ0ppEK4k/riTrwqQDO9wUoBDb8YD1LrBdppeDm89cmmm4BeqaFCBKxRRNTU9X5tLum8wytalyVJ0yUuLrf/kVJ118JEmeZ5exMElxfzv1gOatfzmscfVIoFikeLrC6CohPF1k4UFBd0os2qJ66zIo2xOrCqigA7g2vCA/unC3FnklqS3cab1nhBgSnZ1I4sAXD69VzwP3OdGRfb2KIWyIrIKudxycWh3iZUNFQlfD6RMbFYjAsHNiSIKxErzb6YFkcshGO1eQGgHta8AtAD3rBb5DIC5G+70PMTiwd2fFMi23E9MLSAdOjYZU8AqfEcvjamdmaHS0t76WW9dGxPFPFef60YPTCIgb6IlTmD30xsnQDwBN9zQqkUMyMH+T/frgqimJhzwfAoyT2xhjI16RvoQKz6TtjZFMcCa9mbaKvhKs1JQX6+ELUgBRZRQ6UgJTYkwvixExajkRfoY8SBulD2ShU0Um1QKooMy00koUrW1KfAx7IjtX+QOhkz4p1BB5IOLIrkdXqiOFETz1aDlwBZ80J9CSloRNoLrxotPv5IC+GldPAwa4IK6erraNQ17+xGiBAFSuOl6uiv3ApnhXb1QuXElgckEslasLd3gQ0j0piVTXQr8sPdK+o20dhda8ggxKs7q3GihhW6lrEVkvCpW4rq24hWz0Jh5ymuSxyeI8QE2k9R9RFMYm+VCfqophMymzI4YWU2QicmGeKcDQJo4UTWcykMuQ0J+mhP02KOHKP6pWMGGAquD8DCYf8qempWVEdhBa+Z9M6tkrPLB2Y2xBijOmkrhHbLS1+fTX4rGbEcBlOssjVWZbVzldso+9yr9hHy1VkUtAGdkIWokeW7hA6rWEh2+nxXiTfbKFbOzRbII5tiRc7f7s4jv6vvv2PwaJ5aYftxy8kZyTGZG2I+/1f54liNg==

</p>
</details>

**Comment by Wertoyou** [comment]
This is a simpler example: <details><summary>Blueprint string</summary>
<p>
0eNqdlN1qhDAQhd9lrmMxcdU2r1JK0d1hCbhJSGJZEd+9UVtZ/EHNlSYy35lzZKaFsqpRGyEd8BbEVUkL/LMFK+6yqPo712gEDsLhAwjI4tGf8KkNWhtZXQnn0EBHQMgbPoHTjhwud6aQVivjohIr9wJh3RcBlE44gWNDw6H5lvWj9HKcbrdCQCvrC5Xs9T0sit9SAo1/YV7hJgxex6+XvtUZmJ0AT9xkn5ssuLW3au5G+edof8Gn612TKVSp6z61hdhlL+mllUEq3veRBviI6BqdTT5U7TaMZKeN/GlFdN9KHpjSnM1W2O/Bv3uWUnYgpY/TRo6HROOAgTgwZ5QGpn+kZxacPt2atf/0/V4adhl/2ZwEftDYoSBPYpplOWNp1nW/ZRLRCA==
</p>

**Comment by d4rkc0d3r** [comment]
Since my tool does not simulate two lanes per belt it can not model side loading on underground belts. I promoted the warning to an error since the values it does compute are just flat out wrong in that case.
